spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  
  sql:
    init:
      mode: never  # DatabaseInitializer로 대체
  
  security:
    user:
      name: admin
      password: admin

server:
  port: 9090
  servlet:
    context-path: /api

jwt:
  secret: mySecretKey123456789012345678901234567890
  expiration: 86400000 # 24시간

logging:
  level:
    '[com.example]': DEBUG
    '[org.springframework.security]': DEBUG

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.loginbackend.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl